variables:
# uncomment for the pipeline debug purpose
# CI_DEBUG_TRACE: "true"
  CI_IMAGE: gitlab.int.toradex.com:4567/philippe.schenker/linux-toradex/ci-kernel-builder:latest
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build-uboot

build_u-boot:
  stage: build-uboot
  image: $CI_IMAGE
  variables:
    GIT_STRATEGY: fetch
    GIT_DEPTH: "1"
  script: |
    tools/buildman/buildman toradex || ret=$?
    if [[ $ret -ne 0 && $ret -ne 129 ]]; then
      tools/buildman/buildman -sdeP ${BUILDMAN};
      exit $ret;
    fi;
